/**
 * The shared contract. This file RE-EXPORTS generated types and never
 * redefines a shape.
 *
 * `sops.md` §7: redefining a type turns a compile-time contract break into a
 * runtime failure in front of a user. A hand-written `type User = {...}` looks
 * identical to this until the backend renames a field — at which point the
 * generated schema changes, the local copy does not, `tsc` stays green, and the
 * app breaks at runtime for whoever is signed in.
 *
 * `schema.d.ts` is generated by `npm run gen:api` against a RUNNING backend.
 * Never hand-edit it; edits vanish on the next generation and take the drift
 * alarm with them.
 */

import type { components } from './schema';

type Schemas = components['schemas'];

/** Returned by both `POST /auth/login` and `GET /auth/me`. */
export type CurrentUser = Schemas['CurrentUser'];

export type LoginRequest = Schemas['LoginRequest'];
export type CreateUserRequest = Schemas['CreateUserRequest'];
export type UserCreated = Schemas['UserCreated'];

/**
 * The single failure envelope. Every error the API returns has this shape
 * (`AUT-14`), so a client parses errors once.
 *
 * Render `error.message` — it names the remedy (`AUT-13`). Do not substitute
 * local copy; the backend deliberately returns an identical body for all three
 * login failures, and rewording them client-side reintroduces the leak.
 */
export type ErrorResponse = Schemas['ErrorResponse'];
export type ErrorBody = Schemas['ErrorBody'];
