/**
 * The shared contract. This file RE-EXPORTS generated types and never
 * redefines a shape.
 *
 * `sops.md` §7: redefining a type turns a compile-time contract break into a
 * runtime failure in front of a user. A hand-written `type User = {...}` looks
 * identical to this until the backend renames a field — at which point the
 * generated schema changes, the local copy does not, `tsc` stays green, and the
 * app breaks at runtime for whoever is signed in.
 *
 * `schema.d.ts` is generated by `npm run gen:api` against a RUNNING backend.
 * Never hand-edit it; edits vanish on the next generation and take the drift
 * alarm with them.
 */

import type { components } from './schema';

type Schemas = components['schemas'];

/** Returned by both `POST /auth/login` and `GET /auth/me`. */
export type CurrentUser = Schemas['CurrentUser'];

export type LoginRequest = Schemas['LoginRequest'];
export type CreateUserRequest = Schemas['CreateUserRequest'];
export type UserCreated = Schemas['UserCreated'];

/**
 * The single failure envelope. Every error the API returns has this shape
 * (`AUT-14`), so a client parses errors once.
 *
 * Render `error.message` — it names the remedy (`AUT-13`). Do not substitute
 * local copy; the backend deliberately returns an identical body for all three
 * login failures, and rewording them client-side reintroduces the leak.
 */
export type ErrorResponse = Schemas['ErrorResponse'];
export type ErrorBody = Schemas['ErrorBody'];

// --- Phase 1: the domain read model -----------------------------------------

/** List representation. Carries no items or issues. */
export type OrderSummary = Schemas['OrderSummary'];

/** One order with its items and issues. */
export type OrderDetail = Schemas['OrderDetail'];

export type OrderItem = Schemas['OrderItemOut'];
export type OrderIssue = Schemas['OrderIssueOut'];
export type Customer = Schemas['CustomerOut'];

/**
 * `balance` is derived server-side (`AUT-11`) and is zero until Phase 2 adds
 * transactions. **A zero here is a real zero, not a missing value** — render it
 * as a balance of zero, never as "no balance".
 */
export type Account = Schemas['AccountOut'];

export type ReportIssueRequest = Schemas['ReportIssueRequest'];

/**
 * One page of results. `total` counts only rows the caller may see, so it is the
 * count to display — never `items.length`.
 */
export type OrderPage = Schemas['Page_OrderSummary_'];

// --- Phase 2: the financial core --------------------------------------------

/**
 * A backend-calculated figure. `basis` carries the itemisation the sum was taken
 * over — **render it**. An approver shown only a total is rubber-stamping; one
 * shown the SKUs, quantities and unit amounts is reviewing.
 */
export type Adjustment = Schemas['AdjustmentOut'];

/**
 * The 202 body from `POST /credits`.
 *
 * `outcome` is the literal `APPROVAL_REQUIRED`. This is a **successful** result
 * meaning a proposal was recorded and **nothing was applied**. Rendering it as
 * success is the single most likely defect in this codebase: it looks correct in
 * every screenshot and is discovered by a customer who was told they had been
 * credited and had not.
 */
export type ApprovalRequired = Schemas['ApprovalRequiredOut'];

/**
 * A queue row. `is_expired` is evaluated server-side on read (`AUT-11`), so a
 * row can arrive already expired with no write having happened — render it as
 * expired and offer no approve control.
 */
export type ApprovalRequest = Schemas['ApprovalRequestOut'];

/** A credit that actually exists. Reaching this IS a completion. */
export type Credit = Schemas['CreditOut'];

/** Paginated credit history. `total` is the server's count, never items.length. */
export type CreditPage = Schemas['Page_CreditOut_'];
